export const FETCH_CHALLENGES = 'FETCH_CHALLENGES',
    ADD_CHALLENGE = "ADD_CHALLENGE",
    UPDATE_UPVOTES="UPDATE_UPVOTES",
    REDUCE_UPVOTES="REDUCE_UPVOTES",
    WITHDRAW_FROM_CHALLENGE="WITHDRAW_FROM_CHALLENGE",
    JOIN_CHALLENGE="JOIN_CHALLENGE";